services:
  - type: web
    name: p2p-file-system
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        value: "*"
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health
